### PR TITLE
add OGP meta tags

### PR DESCRIPTION
**Pull request by darknao**
Make this:
image

Into this:
image

### CODE REVIEW

**Comment by t0xic0der** [comment]
Hi @darknao, I want to make one small suggestion. 

As the project is (unironically) called Meetbot Logs, it would be rather helpful to call the Logs as "Meetbot Logs - Logs" and Minutes as "Meetbot Logs - Minutes" to ensure the consistency between the actual project name and the functional name of the page.

**Comment by darknao** [comment]
@t0xic0der: sounds fair. And to avoid repetition, I propose this middle ground: Just use "Meetbot Logs" as the title. The type of logs (logs or minutes) is already mentioned in the description line just below.

**Comment by darknao** [comment]
After some thought, `og:title` is supposed to be for the content title as opposed to the website name.
For the site name, there is actually an `og:site_name` tag available.
Here is how it looks:
image

**Review by t0xic0der — APPROVED** [review]
LGTM

**Pull request merged**
