### PR TITLE
Change instructions in Readme.md file

### PR DESCRIPTION
**Pull request by subhangi2731**
Changed the setup instructions in Readme file using poetry(dependency management and packaging in Python)

### CODE REVIEW

**Comment by subhangi2731** [comment]
@t0xic0der @darknao I changed the instructions and updated it according to the poetry installations. Please check and let me know

**Comment by subhangi2731** [comment]
@t0xic0der @darknao feel free to let me know if this requires any changes and is ready to be merged

**Review by t0xic0der — APPROVED** [review]
Please remove the `.vscode/settings.json` and `requirements.txt`. Once done, it should be ready to be merged.

**Comment by subhangi2731** [comment]
@t0xic0der deleted both the files. Now you can merge

**Pull request merged**
