### PR TITLE
Add logging for mote mod_wsgi

### PR DESCRIPTION
**Pull request by cydrobolt**
#97 
@puiterwijk, can you review this and see if this could work?

### CODE REVIEW

**Comment by puiterwijk** [comment]
Is there any reason why it would be a separate logfile?
The standard apache error log would be most ideal since it'd automatically get rotation rules and sync.

**Comment by cydrobolt** [comment]
@puiterwijk hm, you're right. What's the default `LogLevel`? Maybe that's all we need to fix the issue. Or perhaps no errors have been raised in the app so far?

**Comment by puiterwijk** [comment]
Well, the app was throwing 500's for a long time this afternoon and I couldn't find any logs.

**Comment by cydrobolt** [comment]
Ah. Weird. The default `httpd` LogFile has been reliable for me in the past. I'm not sure what could've changed

**Comment by puiterwijk** [comment]
The homepage. https://meetbot.fedoraproject.org/

**Pull request closed without merging**
