### PR TITLE
Format the date strings in the listing 

### PR DESCRIPTION
**Pull request by subhangi2731**
In this issue, I have formatted the date strings and grouped according to year and month. I have also attached a screenshot where now the newly formatted date time looks like this. 

Fixes issue #188 
Screenshot from 2021-10-18 23-28-18

### CODE REVIEW

**Comment by t0xic0der** [comment]
@subhangi2731, the branch name does not quite define the function that branch performs. I'd suggest naming branches more aptly.

**Comment by subhangi2731** [comment]
yes ok understood @t0xic0der I will create the branch according to function of the issue

**Comment by subhangi2731** [comment]
@t0xic0der Can I close this pr and create a new one with new branch name and then after changing listing I will add new code

**Comment by t0xic0der** [comment]
Why? Just add more commits to this PR.

**Comment by subhangi2731** [comment]
Okay thanks got it will add commits @t0xic0der

**Comment by subhangi2731** [comment]
@t0xic0der thanks for your review. I will do the changes now as you suggested.

**Comment by subhangi2731** [comment]
Screenshot from 2021-10-20 12-55-53
Screenshot from 2021-10-20 12-56-21
Screenshot from 2021-10-20 13-01-49

**Comment by subhangi2731** [comment]
@t0xic0der I changed the format both in the header and listing and did the changes as said by you. Can you please review now and let me know if everything is done?

**Comment by subhangi2731** [comment]
@t0xic0der @darknao please check I have updated and let me know

**Comment by subhangi2731** [comment]
Screenshot from 2021-10-21 18-36-09
Screenshot from 2021-10-21 18-36-50

**Pull request merged**
