### PR TITLE
Separate the configuration in env files

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
This is based on issue #180 

A env file has made used to specify the configuration details for the application

python dotenv is used for reading the configs from a .env and used in respective areas of the codebase

sample .env.example has been added to the repository with the previous values 

requirements.txt has been updated

### CODE REVIEW

**Comment by mscherer** [comment]
So, the code is correct, but I think the configuration naming is not very clear. 

For example "BASE_URL". For other software (like Hugo or Zola), this would be the base url of the current software, eg the URL that will be added in generated link. But here, that's the MEETBOT variable, not BASE_URL.

And BASE_URL is the URL used to query datagrapper, so maybe a more descriptive name could help (for that and MEETBOT ).

**Comment by DiptoChakrabarty** [comment]
> So, the code is correct, but I think the configuration naming is not very clear.
> 
> For example "BASE_URL". For other software (like Hugo or Zola), this would be the base url of the current software, eg the URL that will be added in generated link. But here, that's the MEETBOT variable, not BASE_URL.
> 
> And BASE_URL is the URL used to query datagrapper, so maybe a more descriptive name could help (for that and MEETBOT ).

Shall I rename them to DATAGREPPER_BASE_URL and FEDORA_PROJECT_MEETBOT

**Comment by mscherer** [comment]
I think MEETBOT could be BASE_URL, since that's the meaning of the variable for Hugo, Zola, etc (eg, the base url when creating the website). 

There is no (IMHO) reason to have FEDORA_PROJECT in the name, especially since that's supposed to be reusable by others.

**Comment by Zlopez** [comment]
Wouldn't it be better to use config file (for example https://github.com/fedora-infra/the-new-hotness/blob/master/hotness/config.py) instead of env variables?

**Comment by DiptoChakrabarty** [comment]
Should I convert to dictionary format I have already separated the config to different location

**Comment by DiptoChakrabarty** [comment]
Hey are there any changes that needs to be done here

**Comment by t0xic0der** [comment]
@DiptoChakrabarty, we are looking for adding a config module, say `config.py` instead of a `.env` file. Could you please see if you can rework the code for that?

We already set the label `hacktoberfest-accepted` on your PR so as to ensure that even in the unfortunate circumstance of us not being able to merge your PR, your efforts should not go in vain.

**Comment by DiptoChakrabarty** [comment]
Okay yes Ill try that

**Comment by DiptoChakrabarty** [comment]
You merged another PR even though I started at it earlier and my solution is like you requested it :(

**Comment by t0xic0der** [comment]
@DiptoChakrabarty, this issue ticket fell under one of the quantifiable tasks that our selected intern for Outreachy, @subhangi2731 had to perform. Hence, even if we had your PR come in way before the one she made - we could not be in a position to merge yours.

I did mention of the likeliness of not being able to merge your PR in the second paragraph of https://github.com/fedora-infra/mote/pull/189#issuecomment-955826997. I appreciate the efforts you put into this PR and you have my sincere apologies for not being able to take up your contributions.

**Pull request closed without merging**
