### PR TITLE
Add FZUG (#fedora-zh)

### PR DESCRIPTION
**Pull request by alick**
Please let me know if there is the right way to add a new channel.

### CODE REVIEW

**Comment by cydrobolt** [comment]
Thanks @alick :)

**Comment by cydrobolt** [comment]
It seems like most of your meetings occur in `#fedora-zh`, not categorized under a specific team/meeting name. We're still working on clustering these meetings into one. See #79

**Comment by alick** [comment]
@cydrobolt yeah, all the meetings happen in `#fedora-zh`. That's for the local community in China.

I thought the alias part is functional and I added various used meeting names there. Guess we'll stick to one meeting name in the future.

**Comment by cydrobolt** [comment]
The alias does help propagate certain changes (such as the friendly name), but you would still have to search for "fedora-zh" to find your meetings until they are bundled together (ticket 79)

Thanks :)

**Pull request merged**
