### PR TITLE
Version bumped flask to 1.1.2

### PR DESCRIPTION
**Pull request by nasirhm**
Version Bumping from flask 0.10.1 to 1.1.2 to make sure to work on the latest framework and use it's functionalities.

Ticket: https://github.com/fedora-infra/mote/issues/138

cc: @HiraTariq-01

### CODE REVIEW

**Review by jwflory — APPROVED** [review]
The change is easy enough to me. This can be merged, but the merge conflicts in this Pull Request need to be resolved. I suggest not hand-resolving this merge conflict, but instead deleting and remaking the `Pipfile.lock` file to fix the merge conflict.

Approving for now, once the merge conflict is resolved, we can push this through.

**Review by t0xic0der — APPROVED** [review]
I'm surprised as to how consistent Flask is, with respect to the code-level changes they introduce on every version change. The changes made in this PR are a worthy proof of it. :smile:

**Comment by t0xic0der** [comment]
Retain the hash from your branch over the one from the master - as it is of the recent version. Once that is done, we are good to merge this one.

**Review by ramyaparimi — APPROVED** [review]

**Review by jwflory — APPROVED** [review]
OK, merge conflict resolved! We all approved this Pull Request already and discussed in the developer meeting, so I am just gonna merge this. 🎬 

Thanks @nasirhm!

**Pull request merged**
