### PR TITLE
add calendar view

### PR DESCRIPTION
**Pull request by subhangi2731**
The calendar view is added with Vanilla plugin and add event.

### CODE REVIEW

**Comment by subhangi2731** [comment]
Screenshot from 2021-12-15 09-48-58

**Review by t0xic0der — CHANGES_REQUESTED** [review]
Please correct me if I'm mistaken but I do remember to have discussed the following three points with you during the yesterday's weekly Websites and Apps team meeting.
1. We agreed upon the use of a dedicated calendar JS library and not a vanilla one to simplify our dealings with the calendar element and avoid any issues there may arise due to a ground-up implementation.
2. We talked about fetching the meetings from the endpoint where the recent meetings are acquired and place them on the calendar for dates extending upto one month. 
3. As Mote is supposed to be a simple application for accessing information about meetings, having any interaction with the calendar to add events DO NOT serve any purpose.

I do not think that this pull request satisfies any of the aforementioned points.

**Comment by subhangi2731** [comment]
@t0xic0der sure this pr can be closed then I will send a different pr with full calendar plugin

**Comment by darknao** [comment]
I don't think we need this anymore.

**Pull request closed without merging**
