### PR TITLE
Elaboration of setup commands 

### LINKED ISSUE #196: Elaborate explanations of setup commands
Elaborate explanations of setup commands

### PR DESCRIPTION
**Pull request by jet2018**
Step by step procedure for setting up this project locally in a development environment . Resolves #196

### CODE REVIEW

**Comment by darknao** [comment]
Thanks for your first contribution @jet2018 :)

I see you're still making changes to this PR, so I'll wait before making my final review.  
One thing I can notice, is there are some markdown syntax issues in your README.md (malformed links and lists, missing line feeds).  
You might have fixed most of them since then, but just in case :  
- Please read https://www.markdownguide.org/basic-syntax/
- Don't hesitate to use the internal Github editor to edit and preview your changes. It can be very helpful for spotting formatting errors, especially for Markdown files.

**Comment by jet2018** [comment]
> Just a few things to address and I think we should be good. Please note: This PR is focused on README.md and its related ticket #196. Modification to all other files are unrelated to the linked issue. Can you please create a second PR with the other changes you made, and remove them from this one ?

How do I remove those specific files, have tried but everytime I commit my changes, it seems they are redirected to this PR, sorry but you know amatuer issues, thank you

**Comment by jet2018** [comment]
@darknao I hope now the readme is ready to be merged as I have reverted the unwanted changes again

**Comment by darknao** [comment]
not sure what happened, but all html files that were removed, are now back.

**Pull request merged**
