### PR TITLE
Sort search results by most-recent-meetings first.

### LINKED ISSUE #32: search should sort results by most-active-entries first
if you search for just 'design' you see that the first two results it returns have only old entries.. but the third entry is the one you want with the most recent stuff.

### PR DESCRIPTION
**Pull request by ralphbean**
Fixes #32.

### CODE REVIEW

**Comment by Cydrobolt** [comment]
This looks pretty good! Have you tested this yourself this?

**Comment by ralphbean** [comment]
> Have you tested this yourself?

I have!  It's working :)

**Comment by Cydrobolt** [comment]
@threebean maybe we should also add the dependency to the spec? :)

**Comment by ralphbean** [comment]
> @threebean maybe we should also add the dependency to the spec? :)

Yes!  I forgot the .spec file was included in the repo.

**Comment by Cydrobolt** [comment]
I added it for you :)

**Pull request merged**
