### PR TITLE
Fix syntax highliting in meeting logs

### PR DESCRIPTION
**Pull request by mymindstorm**
| Before | After |
| ------ | ----- |
| image | image |

### CODE REVIEW

**Comment by jwflory** [comment]
Wow, this is a super easy bugfix and would readability so much easier. I'd love to see this make it to production!

**Comment by cydrobolt** [comment]
Looks good to me. I haven't been active in a while and don't have commit access anymore, so someone else will have to take this change to production.

**Comment by pypingou** [comment]
> Looks good to me. I haven't been active in a while and don't have commit access anymore, so someone else will have to take this change to production.

That's something we can fix :)

**Comment by pypingou** [comment]
@cydrobolt welcome back :)

**Review by Zlopez — APPROVED** [review]

**Pull request merged**
