### PR TITLE
issue-170-added footer -siddhantkhariwal

### PR DESCRIPTION
**Pull request by siddhantkhariwal**
### DESCRIPTION
Added footer with all the footer links and RedHat logo.
social media logos are showing a blank square.
issue- #170

### CODE REVIEW

**Review by t0xic0der — CHANGES_REQUESTED** [review]
I have kept both the sites, side-by-side for comparison.

image

Some changes, I'd suggest

- Remove the margin from the top side now that we have the footer?
- Align the links and link headers to the left side
- Ensure that the underline beneath the links are visible only when they are hovered upon
- Bring the three stacks a bit more close to each other
- Remove the unfinished implementation of Facebook and Twitter logos for now
- Remove the text that says `Fragment © 2021 Akashdeep Dhar and others` at the bottom
- Reduce the font size to make it fall in line with the one of the description
- Ensure that the rows stack atop each other when the width decreases beyond a certain limit

**Comment by siddhantkhariwal** [comment]
Hey, @t0xic0der I have made the changes, please check it and let me know if any other changes are remaining.

**Comment by siddhantkhariwal** [comment]
> Attaching the updated screenshot here for reference
> 
> image
> 
> * The top side margin is still there. Please remove it.
> * The group of links on the bottom looks a bit inclined towards the left side. Note that I'm not talking about the alignment of one link but the group as a whole - which should be in the center.
> * The font sizes have stayed the same. Please make it small enough to fall in line with the one of the description.
> * I tried progressively reducing the width and the rows do not stack atop each other. Please ensure that happens.

Hey @t0xic0der , I have done the changes except for the responsive stack one. I am having trouble doing that.

**Comment by siddhantkhariwal** [comment]
@t0xic0der have you checked this?

**Comment by t0xic0der** [comment]
Closing this as stale

**Pull request closed without merging**
